Unity/exercises/Lab06/end/StocksTicker/Controllers/StocksTickerController.cs
//===============================================================================
// Microsoft patterns & practices
// Enterprise Library 6 and Unity 3 Hands-on Labs
//===============================================================================
// Copyright © Microsoft Corporation.  All rights reserved.
// THIS CODE AND INFORMATION IS PROVIDED "AS IS" WITHOUT WARRANTY
// OF ANY KIND, EITHER EXPRESSED OR IMPLIED, INCLUDING BUT NOT
// LIMITED TO THE IMPLIED WARRANTIES OF MERCHANTABILITY AND
// FITNESS FOR A PARTICULAR PURPOSE.
//===============================================================================

using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using StocksTicker.StockQuoteServices;

namespace StocksTicker.Controllers
{
    public class StocksTickerController : Controller
    {
        private IStockQuoteService service;

        public StocksTickerController(IStockQuoteService service)
        {
            this.service = service;
        }

        public ActionResult Index()
        {
            var quotes = this.service.GetQuotes(this.GetSymbols()).Values.ToList();

            return View(quotes);
        }

        public ActionResult AddStock(string symbol)
        {
            if (!string.IsNullOrWhiteSpace(symbol))
            {
                var symbols = GetSymbols();

                symbols.Add(symbol.Trim().ToUpperInvariant());
            }

            return RedirectToAction("Index");
        }

        private IList<string> GetSymbols()
        {
            var symbols = (IList<string>)HttpContext.Session["symbols"];
            if (symbols == null)
            {
                symbols = new List<string>();
                HttpContext.Session["symbols"] = symbols;
            }
            return symbols;
        }
    }
}

Unity/exercises/Lab06/end/StocksTicker/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    @RenderSection("meta", required: false)
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    @RenderBody()

    @Scripts.Render("~/bundles/jquery")
    @RenderSection("scripts", required: false)
</body>
</html>

Unity/exercises/Lab06/end/StocksTicker/Views/StocksTicker/Index.cshtml
@model System.Collections.Generic.IList<StocksTicker.StockQuoteServices.StockQuote>

@{
    ViewBag.Title = "Simulated stocks ticker";
}

<h2>Simulated stocks ticker</h2>

@using (Html.BeginForm("AddStock", "StocksTicker", FormMethod.Post))
{
    <div>
        <span>Symbol</span>
        <input name="symbol" type="text" />
        <input type="submit" value="Subscribe" />
    </div>
    <br />
    <br />
}

@if (Model.Count > 0)
{
    <div>
        <table cellspacing="0" cellpadding="5" rules="all" border="1" style="border-collapse: collapse;">
            <tr>
                <th scope="col">Symbol</th>
                <th align="right" scope="col">Volume</th>
                <th align="right" scope="col">Last</th>
                <th align="right" scope="col">Change</th>
                <th align="right" scope="col">Change %</th>
                <th scope="col">Update</th>
            </tr>
            @foreach (var quote in Model)
            {
                <tr>
                    <td>@quote.Symbol</td>
                    <td align="right">@quote.Volume</td>
                    <td align="right">@quote.Last</td>
                    <td align="right">
                        <span style="color: @ColorForValue(quote.Change);">@quote.Change</span>
                    </td>
                    <td align="right">
                        <span style="color: @ColorForValue(quote.Change);">@quote.PercentChange</span>
                    </td>
                    <td>4:37:36 PM</td>
                </tr>
            }
        </table>
    </div>
}


@section meta {
    <meta http-equiv="refresh" content="30" />
}

@functions {

    private string ColorForValue(double value)
    {
        if (value >= 0d)
        {
            return "Green";
        }
        else
        {
            return "Red";
        }
    }

}